CREATE TABLE IF NOT EXISTS users (
	id SERIAL PRIMARY KEY,
	username TEXT UNIQUE NOT NULL,
	password TEXT NOT NULL,
	email TEXT UNIQUE NOT NULL,
	phone_number TEXT NOT NULL,
	address TEXT NOT NULL,
	role TEXT NOT NULL
);